version: '3.8'
services:
  zookeeper:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile-zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  apache:
    build:
      context: ./kafka
      dockerfile: Dockerfile-kafka
    ports:
      - "80:80"

volumes:
  zookeeper_data:
  zookeeper_datalog:
